%error-verbose
%require "3.0"

%code requires
{
    #include "html_tag.hpp"
}

%code top
{
    #include <iostream>
    #include <string>
    #include <boost/algorithm/string.hpp>
}

%{
using namespace std;
extern int yylex();
extern int yyparse();
void yyerror(const char* msg) {
  fprintf(stderr, "%s", msg);
}
%}

%union {
  char *sval;
  HtmlTag *tag;
}

%token DOCTYPE
%token TAG_NAME
%token TAG_CLASS
%token DIV
%token ATTRIBUTE_NAME
%token STRING_LITERAL
%token IDENTIFIER

%%

haml
    : fragment
    | haml fragment
    ;

fragment
       : html_tag
       ;

html_tag
       : html_tag_start '{' html_attribute_list '}'
       | html_tag_start
       | DIV
       ;

html_tag_start
             : TAG_NAME TAG_CLASSES
             | TAG_NAME
             ;

TAG_CLASSES
          : TAG_CLASS TAG_CLASSES
          | TAG_CLASS
          ;

html_attribute_list
                  : html_attribute
                  | html_attribute_list ',' html_attribute
                  ;
html_attribute
             : ATTRIBUTE_NAME ':' attribute_value
             ;

attribute_value
              : STRING_LITERAL
              | function_call
              ;

function_call
            : IDENTIFIER
            ;


%%

int main(int argc, char** argv) {
  yyparse();
}
